plaidev/easy-dc-dash

- docs/example/dashboard-01/index.html
- libs/chart/_base.js
- libs/chart/components/reset-button.vue
- libs/chart/data-table.vue
- libs/chart/filter-stacked-bar.vue
- libs/chart/index.js
- libs/chart/list-row.vue
- libs/chart/ordinal-bar.vue
- libs/chart/rate-line.vue
- libs/chart/reset-all-button.vue
- libs/chart/segment-pie.vue
- libs/chart/stacked-bar.vue
- libs/chart/stacked-lines.vue
- libs/chart/week-row.vue
- libs/utils/index.js
**追加**
- chartごとにfilterを解除するボタン(reset-button.vue)
- 全chartのfilterを解除するボタン(reset-all-button.vue)
**bugfix**
- bar chartの選択状態
classがぶつかっていた
- list row の表示制限
displayRowsのままになっている箇所を修正
**変更**
- bootstrap4にした
- それに伴いstyleをいじった
@otolab よろしくお願いします。
> Add reset button

- libs/chart/_base.js
- libs/chart/multi-dimension-pie.vue
- libs/chart/ordinal-bar.vue
- libs/chart/segment-pie.vue
- libs/chart/series.vue
- libs/chart/stacked-bar.vue
- libs/utils/index.js
- pie-chart
- pieの割合をstartAngle,endAngleから計算
- bar-chart
- ordinalとstackedでdimensionにdateが渡された時に日付が変換されない問題を修正
- rate-lineなど割合を値に持つ場合に小数点2桁で丸めるように修正
- d.x, d.yが存在するが値が0の時にエラーになる問題を修正
@otolab 
レビューお願いします
> fix tooltip format

- libs/chart/_base.js
- libs/chart/_composite.js
- libs/chart/bubble.vue
- libs/chart/data-table.vue
- libs/chart/filter-stacked-bar.vue
- libs/chart/geo-jp.vue
- libs/chart/heat-map.vue
- libs/chart/list-row.vue
- libs/chart/multi-dimension-pie.vue
- libs/chart/number-display.vue
- libs/chart/segment-pie.vue
- libs/chart/week-row.vue
- libs/components/card.vue
- libs/components/krt-dc-tooltip.vue
- libs/utils/index.js
- package.json
- yarn.lock
> CSSのローカライズが働くようにする

- docs/example/chart/area-line.html
- docs/example/chart/multi-lines.html
- libs/chart/_base.js
- libs/chart/_composite.js
- libs/chart/area-line.vue
- libs/chart/index.js
- libs/chart/multi-lines.vue
- libs/chart/reset-all-button.vue
- libs/chart/stacked-lines.vue
- libs/utils/index.js
> area-line, multi-linesの追加

- docs/example/chart/multidim-pie.html
- libs/chart/_base.js
- libs/themes/default/index.js
- package.json
- yarn.lock
> チャート固有のlayoutの微調整を可能に

- docs/example/dashboard-02-jp-map/index.html
- libs/chart/_base.js
- libs/chart/data-table.vue
- libs/chart/geo-jp.vue
- libs/chart/multi-dimension-pie.vue
- libs/chart/segment-pie.vue
- libs/components/card.vue
- libs/components/reset-button.vue
- libs/themes/default/index.js
- package.json
- yarn.lock
refs #39 
* リサイズへの対応
* fullscreen状態の追加
> add fullscreen mode

- docs/example/chart/chart-link.html
- libs/chart/_base.js
- libs/chart/multi-dimension-pie.vue
- libs/components/chart-link.vue
- libs/components/reset-button.vue
- libs/store.js
refs #47 
docs/example/chart/chart-link.html
https://github.com/plaidev/easy-dc-dash/pull/52/files#diff-cbeb9f768030aaae422bbe59972ab7b0
```
<chart
:display-link=true
link-formatter='formatterName' // option
></chart>
```
**dimensionのvalueからlinkを生成する**
- valueがlinkなら `:display-link=true`のみで良い
- valueを使って任意のlinkを生成したい場合はlinkFormatterを定義する
- valueをクエリパラメータに用いる
```
EasyDC.Store.registerLinkFormatter('formatterName', (v) => {
return 'https://example.com?' + v
})
```
- labelsを用いてlinkを生成する
```
EasyDC.Store.setLabel({'name' : 'http(s)://~~'})
EasyDC.Store.registerLinkFormatter('formatterName', (v) => {
return EasyDC.Store.getLabel(v)
})
```
> chart click link

- docs/example/dashboard-01/index.html
- libs/chart/_base.js
- libs/themes/default/index.js
#60 
linkFormatter の default定義削除も一緒に入ってます
> xAxis要素が多すぎる時はlabelを自動で隠す

- docs/example/chart/multidim-pie.html
- libs/autorun.js
- libs/store.js
- libs/utils/load-dataset.js
> [base] support auto mapped labels

- libs/chart/_base.js
- libs/components/card.vue
- libs/themes/default/index.js
> [base] add captionHeight

- docs/example/chart/multidim-pie.html
- libs/chart/_base.js
- libs/store.js
- libs/themes/default/index.js
> Themeの切り替えをサポート

- docs/example/chart/multidim-pie.html
- docs/example/dashboard-01/index.html
- libs/chart/_base.js
- libs/chart/bubble.vue
- libs/chart/multi-dimension-pie.vue
- libs/chart/segment-pie.vue
- baseのpropsにshowLabelを追加
- pie-chartとbubble-chartのlabelを消したいという要望があったので、消せるようにした
- hide[X|Y]AxislabelとisShowlabelsがややこしいのでshow[X|Y]AxisLabelsに変更
TODO
- showLabel, showXAxisLabel, showYAxisLabelなどlabel周りのoropsがどうしても多すぎるので整理する
> fix labels

- libs/chart/_base.js
- libs/chart/_coordinateGridBase.js
- libs/chart/geo-jp.vue
- libs/chart/heat-map.vue
- libs/themes/default/index.js
refs #58 
テーマからcolorsが取得できた場合に有効になるようにしました。
> [base] fix color theme

- libs/chart/_base.js
- libs/chart/_composite.js
- libs/chart/multi-lines.vue
- libs/components/card.vue
- libs/themes/default/index.js
> [base] fix bug and degrades

- libs/chart/stacked-lines.vue
> [stacked-lines] fix

- libs/chart/_base.js
- libs/chart/_composite.js
- libs/chart/list-row.vue
- libs/chart/multi-lines.vue
- libs/components/card.vue
> Feature/fix 0.2.2

- libs/chart/_base.js
- libs/chart/_coordinateGridBase.js
> cordination grid baseに軸関係のオプションを寄せた

- docs/example/dashboard-01/index.html
- libs/chart/_base.js
- libs/components/card.vue
- libs/store.js
- libs/themes/default/index.js
> テーマとしてcard設定を持つようにした

- libs/chart/_base.js
- libs/chart/ordinal-bar.vue
> move removeEmptyRows code

- libs/chart/_base.js
> fix defaultTheme

- libs/chart/_base.js
> fix cap tooltip

- libs/chart/list-row.vue
- libs/chart/segment-pie.vue
> list-rowでもremoveEmptyRowsを使わないようにする

- libs/chart/data-table.vue
- libs/components/card.vue
> 親要素がflexであるときwidthを自動調整する

- libs/components/reset-button.vue
refs #107 
* #107 の修正
* フィルタ選択時の色をグレーから緑に変えてみた
> reset buttonのサイズがおかしくなる問題の修正+色変更

- docs/example/dashboard-01/index.html
- libs/chart/_base.js
- libs/chart/data-table.vue
- libs/chart/heat-map.vue
- libs/chart/list-row.vue
closes #82, closes #112 
[list-row] デフォルトでxAxisLabelが斜めになっていない #82 
ヒートマップにもx-axis-label/y-axis-labelを表示したい #112 
@otolab 
レビューお願いします！
> [list-row] rotate xAxisLabel, [heatmap] display x/y axis-label

- libs/chart/number-display.vue
> [number-display] component内でrenderする

- libs/chart/data-table.vue
> テーブルのスキーマ周りの処理、その２

- docs/example/dashboard-01/index.html
- libs/chart/index.js
> [chart] add bar-and-rate chart

- docs/example/dashboard-01/index.html
- libs/chart/csv-download-button.vue
- libs/store.js
- libs/utils/blob-csv.js
refs: #180 
**やったこと**
- ボタンテキストを変えられるようにした
- 出力するCSVのカラムを指定できるようにした
- 出力するCSVの空文字, null, undefinedの扱いを変更した
- `"",null,undefined`の出力時に`"","null","undefined"`と変換していたが、カンマのみ出力するようにした(`,,,`となる)
> CSVダウンロード周りの修正
